### ISSUE TITLE
Port to .net Standard

### ISSUE THREAD

**Issue by 91378246** [Cloet/AsyncClientServer#23]
As far as i can see there wouldn't be any issue to change the target framework to .net standard 2.0. I just tried it (new .net standard project, copy/paste your code) and the only line to change is 
`using System.Diagnostics.Eventing.Reader;`
in AsyncClientServer.Server.AsyncSocketListener which is a unused using.
=> Shouldn't be much work (if you want, i can do it too, just wanted to know, if you would accept it).

As Microsoft is going to dump the .net framework as we know it, this would future prove this code and make it multi platform too.

**Comment by Cloet** [comment]
I’ll take a look at it tomorrow, if I can change it to .Net 2.0 I’ll adjust the code

**Comment by Cloet** [comment]
The AsyncClientServer Library has been converted to .NET Standard 2.0
