### ISSUE TITLE
Generics Send/Receive for typed messages

### ISSUE THREAD

**Issue by moro91** [Cloet/AsyncClientServer#24]
Is it possible to have generics interfaces to send and dispatch incoming messages? I mean, is there a way to register receivers for messages that are of a certain .net type?

**Comment by Cloet** [comment]
So if I understand corretly, you want to know if a message is received from a .NET core application or .Net framework ?

**Comment by moro91** [comment]
I mean a support to send and receive objects. For example:
A client send a PurchaseOrderMessage to the server that has to have registered a PurchaseOrderMessageHandler to receive the message and route it to the proper logic. It could be helpful when you develop complex messaging systems in which strong typing can be really a charm

**Comment by Cloet** [comment]
I have something like that called a  CustomHeaderMessage where you can give a message and a header as message but I haven’t really made an interface for custom messages. It’s a good idea though so i’ll probably implement it.

**Comment by moro91** [comment]
Glad you find it useful! I would be pleased to maybe help you

**Comment by Cloet** [comment]
All help is welcome :)

**Comment by Cloet** [comment]
I've implemented MessageContracts check "Example/NetCore.Console.Client" and "Example/NetCore.Console.Server" for an example of the implementation of IMessageContract.
