### ISSUE TITLE
Use in Winforms

### ISSUE THREAD

**Issue by IlTuoNome** [Cloet/AsyncClientServer#4]
Hi, I downloaded the new version and I noticed that if you try to use the files in Winforms it contains the following errors in compilation:
1) The name 'ZipFile' does not exist in the current context.
2) The type or space name of the name 'ZipArchive' was not found.

In the previous version using Winforms returned no error.

**Comment by Cloet** [comment]
ZipFile and ZipArchive require you to add a refernence to "System.IO.Compression" and "System.IO.Compression.FileSystem". [https://imgur.com/Vwjmjy7](url)

**Comment by IlTuoNome** [comment]
Thanks, I didn't notice this.

**Comment by Cloet** [comment]
Made a quick test in winforms if you need it. [TestClientServer](http://www.mediafire.com/file/cb294ebexbdkeea/TestClientServer.zip/file)
