### ISSUE TITLE
Stopping server

### ISSUE THREAD

**Issue by PROPPO** [Cloet/AsyncClientServer#8]
Hi, how can I stop the server completely?

**Comment by Cloet** [comment]
You can use the .Dispose() method for your server. I've fixed some bugs with the dispose method in the latest commit.

**Comment by PROPPO** [comment]
I have try to install the new version but if i stop the server with .Dispose() i have this problem:
File AsyncSocketListener.cs
Method: OnClientConnect
Error: System.ArgumentNullException: 'The value cannot be null.'  on line 90: lock (_clients)

**Comment by Cloet** [comment]
I've just done an update, can you test now ? If you're still getting an error can you show me the code ?

**Comment by PROPPO** [comment]
Yes, now work but if i restart the server the client not connect to me.
I think if i stop the server and i restart it, it not start for real.

**Comment by Cloet** [comment]
The server checks every 15 seconds if connections are still active, if not it will try to restart the client and reconnect to the client. So it could just be you'll have to wait a bit longer till the client checks it connection and tries to reconnect.

**Comment by PROPPO** [comment]
I'm try but the client debug return me:
Exception generated: 'System.Net.Sockets.SocketException' in System.dll
Exception generated: 'System.Net.Sockets.SocketException' in System.dll
Exception generated: 'System.Net.Sockets.SocketException' in System.dll
Exception generated: 'System.Net.Sockets.SocketException' in System.dll
Exception generated: 'System.Net.Sockets.SocketException' in System.dll

**Comment by Cloet** [comment]
In this example I put a stop and start button for the server but I cannot seem to replicate your problem. Could you give me some more info about what you're doing with the code ?
[link to example project](https://www.mediafire.com/file/y8hr6enh5zs2enq/AsyncClientServer.zip/file)

**Comment by Cloet** [comment]
I've added 'StopListening()' and 'ResumeListening()' to the server. But if you don't want to use the socket in the future you should still use 'Dispose()'

**Comment by PROPPO** [comment]
Hi, i send you my simple project, it have 2 form server/client with 2 buttons Start/Connect and Stop/Close.
Try to run for first the server and connect the client, then to disconnect to client (exception)...
Then try to start the server, close it and restart and try to connect the client, i have this error with the client:
> I'm try but the client debug return me:
> Exception generated: 'System.Net.Sockets.SocketException' in System.dll
> Exception generated: 'System.Net.Sockets.SocketException' in System.dll
> Exception generated: 'System.Net.Sockets.SocketException' in System.dll
> Exception generated: 'System.Net.Sockets.SocketException' in System.dll
> Exception generated: 'System.Net.Sockets.SocketException' in System.dll

[Mediafire](http://www.mediafire.com/file/zzk0g741x2d05ni/TestServerClient.rar/filel)

**Comment by Cloet** [comment]
I'll take a look at it

**Comment by Cloet** [comment]
I've updated the source code in your project, and I'll update the git too. It should work now, if you want to reuse your sockets you can't dispose them.
[Project](http://www.mediafire.com/file/deiw2i3bc4bdp4y/Test.zip/file)
